set_property IOSTANDARD LVCMOS33 [get_ports {data_in_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports LLC_0]
set_property IOSTANDARD LVCMOS33 [get_ports FIELD_0]
set_property IOSTANDARD LVCMOS33 [get_ports VSYNC_0]
set_property IOSTANDARD LVCMOS33 [get_ports HSYNC_0]

set_property PACKAGE_PIN H16 [get_ports {data_in_0[7]}]
set_property PACKAGE_PIN G16 [get_ports {data_in_0[6]}]
set_property PACKAGE_PIN J16 [get_ports {data_in_0[5]}]
set_property PACKAGE_PIN J15 [get_ports {data_in_0[4]}]
set_property PACKAGE_PIN G15 [get_ports {data_in_0[3]}]
set_property PACKAGE_PIN G14 [get_ports {data_in_0[2]}]
set_property PACKAGE_PIN J14 [get_ports {data_in_0[1]}]
set_property PACKAGE_PIN H14 [get_ports {data_in_0[0]}]
set_property PACKAGE_PIN G13 [get_ports LLC_0]
set_property PACKAGE_PIN H13 [get_ports FIELD_0]
set_property PACKAGE_PIN D20 [get_ports VSYNC_0]
set_property PACKAGE_PIN E20 [get_ports HSYNC_0]

set_property PULLDOWN true [get_ports {data_in_0[7]}]
set_property PULLDOWN true [get_ports {data_in_0[6]}]
set_property PULLDOWN true [get_ports {data_in_0[5]}]
set_property PULLDOWN true [get_ports {data_in_0[4]}]
set_property PULLDOWN true [get_ports {data_in_0[3]}]
set_property PULLDOWN true [get_ports {data_in_0[2]}]
set_property PULLDOWN true [get_ports {data_in_0[1]}]
set_property PULLDOWN true [get_ports {data_in_0[0]}]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
